name: Moneycontrol Stock Scanner

on:
  schedule:
    # 9:30 AM – 9:45 AM IST
    - cron: "0,15,30,45 4 * * 1-5"

    # 10:00 AM – 10:45 AM IST
    - cron: "0,15,30,45 5 * * 1-5"

    # 11:00 AM – 11:45 AM IST
    - cron: "0,15,30,45 6 * * 1-5"

    # 12:00 PM – 12:45 PM IST
    - cron: "0,15,30,45 7 * * 1-5"

    # 1:00 PM – 1:45 PM IST
    - cron: "0,15,30,45 8 * * 1-5"

    # 2:00 PM – 2:45 PM IST
    - cron: "0,15,30,45 9 * * 1-5"

    # 3:00 PM – 3:15 PM IST
    - cron: "0,15 10 * * 1-5"

  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scanner
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python allcategories.py
